"""Writer for DHSVM's configuration file.

The DHSVM configuration file is a flat, INI-like text file of
``[SECTION]`` headers containing ``Key = value`` pairs.  Its parser
(``GetInit.c``) is forgiving about whitespace and ordering and treats
``#`` as a comment, but it is *unforgiving* about a key being in the
wrong section or absent when an option requires it -- a missing key
produces ``ReportError(key, 51)`` and an immediate exit.

This module builds the whole file from the objects the rest of
``ww_dhsvm`` produces, so that the many cross-dependencies between
options and required keys are handled once, in code, rather than by hand
in a template.  Examples of those dependencies:

* ``Flow Routing = NETWORK`` requires the three stream files;
* ``Gridded Met data = FALSE`` requires a ``Station File``,
  ``Elevation``, ``North Coordinate`` and ``East Coordinate`` block for
  every station;
* ``Shading = TRUE`` requires monthly shadow maps and a sky-view file;
* ``Number of Soil Types`` must equal the number of ``[SOILS]``
  parameter blocks, and every soil ID in ``soil.bin`` must be ``<=`` it,
  or ``InitTerrainMaps.c`` raises error 32;
* ``Number of Root Zones`` in ``[VEGETATION]`` must equal ``Number of
  Soil Layers`` in ``[SOILS]``.

The writer is the ``ww_dhsvm`` counterpart of Watershed Workflow's ATS
XML generation, which serves exactly the same purpose for a very
different input format.

This is the analog of Watershed Workflow's ``ats_input_spec`` usage in
its Coweeta notebook: a programmatic description of the run, emitted in
the model's native syntax.
"""

from typing import Optional, Dict, List, Any, Sequence
import os
import logging
import datetime
import textwrap

import numpy as np


def _fmt(v) -> str:
    """Format one value the way DHSVM's parser reads it back."""
    if isinstance(v, bool):
        return 'TRUE' if v else 'FALSE'
    if isinstance(v, (list, tuple, np.ndarray)):
        return ' '.join(_fmt(x) for x in v)
    if isinstance(v, (int, np.integer)):
        return str(int(v))
    if isinstance(v, (float, np.floating)):
        f = float(v)
        if f != 0 and (abs(f) < 1e-4 or abs(f) >= 1e7):
            return f'{f:.6e}'
        return f'{f:.6g}'
    return str(v)


class DHSVMConfig:
    """Builder for a DHSVM configuration file.

    Sections are emitted in DHSVM's canonical order.  Keys within a
    section are emitted in insertion order, which keeps the file
    readable and diffable between runs.
    """

    SECTION_ORDER = ['OPTIONS', 'AREA', 'TIME', 'CONSTANTS', 'TERRAIN',
                     'ROUTING', 'METEOROLOGY', 'SOILS', 'VEGETATION', 'OUTPUT']

    def __init__(self, name: str = 'ww-dhsvm'):
        self.name = name
        self.sections: Dict[str, List] = {s: [] for s in self.SECTION_ORDER}
        self.comments: Dict[str, str] = {}

    def set(self, section: str, key: str, value) -> 'DHSVMConfig':
        """Set one key, replacing any previous value for it."""
        section = section.upper()
        if section not in self.sections:
            self.sections[section] = []
        entries = self.sections[section]
        for i, (k, _) in enumerate(entries):
            if k.lower() == key.lower():
                entries[i] = (key, value)
                return self
        entries.append((key, value))
        return self

    def update(self, section: str, mapping: Dict[str, Any]) -> 'DHSVMConfig':
        """Set many keys at once."""
        for k, v in mapping.items():
            self.set(section, k, v)
        return self

    def comment(self, section: str, text: str) -> 'DHSVMConfig':
        """Attach an explanatory comment above a section."""
        self.comments[section.upper()] = text
        return self

    # ------------------------------------------------------------------

    def write(self, filename: str) -> str:
        """Render the configuration file."""
        os.makedirs(os.path.dirname(os.path.abspath(filename)), exist_ok=True)
        bar = '#' * 88

        with open(filename, 'w') as fid:
            fid.write(f'{bar}\n')
            fid.write(f'# DHSVM configuration file -- {self.name}\n')
            fid.write(f'# Generated by WW-DHSVM on '
                      f'{datetime.datetime.now():%Y-%m-%d %H:%M:%S}\n')
            fid.write('#\n')
            fid.write('# Every path below is relative to the directory DHSVM is\n')
            fid.write('# launched from, unless it is absolute.\n')
            fid.write(f'{bar}\n\n')

            for section in self.SECTION_ORDER:
                entries = self.sections.get(section)
                if not entries:
                    continue
                fid.write(f'{bar}\n# {section} SECTION\n{bar}\n')
                if section in self.comments:
                    for line in textwrap.wrap(self.comments[section], 84):
                        fid.write(f'# {line}\n')
                fid.write(f'\n[{section}]\n')

                width = max(len(k) for k, _ in entries)
                for key, value in entries:
                    if value is None:
                        continue
                    if key.startswith('#BLANK'):
                        fid.write('\n')
                        continue
                    if key.startswith('#COMMENT'):
                        fid.write(f'# {value}\n')
                        continue
                    fid.write(f'{key:<{width}} = {_fmt(value)}\n')
                fid.write('\n')

            fid.write(f'{bar}\n# END OF INPUT FILE\n{bar}\n[End]\n')

        logging.info(f'  wrote DHSVM configuration -> {filename}')
        return filename


# ---------------------------------------------------------------------------
# High-level assembly
# ---------------------------------------------------------------------------

def buildConfig(name: str,
                grid,
                start: datetime.datetime,
                end: datetime.datetime,
                timestep_hours: float,
                paths: Dict[str, str],
                soil_blocks: List[Dict[str, Any]],
                veg_blocks: List[Dict[str, Any]],
                stations: Sequence,
                output_dir: str,
                state_dir: Optional[str] = None,
                n_soil_layers: int = 3,
                constants: Optional[Dict[str, Any]] = None,
                options: Optional[Dict[str, Any]] = None,
                output_pixels: Optional[List[Dict[str, Any]]] = None,
                state_dates: Optional[List[datetime.datetime]] = None,
                map_variables: Optional[List[Dict[str, Any]]] = None,
                shading: bool = False,
                canopy_gapping: bool = False,
                routing_neighbors: int = 4) -> DHSVMConfig:
    """Assemble a complete DHSVM configuration.

    Parameters
    ----------
    name : str
        Run name, used in the header.
    grid : ModelGrid
        Supplies the ``[AREA]`` block.
    start, end : datetime.datetime
        Simulation period, in the same time convention as the forcing
        (UTC, as written by :mod:`ww_dhsvm.meteorology`).
    timestep_hours : float
        Model timestep.  Must divide 24 and must not exceed the forcing
        interval.
    paths : dict
        Input file paths, keyed ``'dem'``, ``'mask'``, ``'soil'``,
        ``'soil_depth'``, ``'veg'``, ``'stream_map'``,
        ``'stream_network'``, ``'stream_class'``, and optionally
        ``'canopy_gap'``, ``'shadow_path'``, ``'skyview'``.
    soil_blocks, veg_blocks : list of dict
        From :mod:`ww_dhsvm.soils` and :mod:`ww_dhsvm.vegetation`.
    stations : sequence of MetStation
        Forcing stations, already written to disk.
    output_dir : str
        Where DHSVM writes results.  **Must exist before DHSVM runs** --
        it does not create it, and fails with "Cannot open file" if it
        is missing.
    state_dir : str, optional
        Initial-state directory.  Defaults to ``output_dir``.
    constants : dict, optional
        Overrides for the ``[CONSTANTS]`` section.
    options : dict, optional
        Overrides for the ``[OPTIONS]`` section.
    routing_neighbors : int, optional
        4 (default) or 8.  Must match how the DHSVM binary was compiled:
        the ``DHSVM_D8`` CMake option selects the stencil, and this key
        only takes effect in builds that support it.

    Returns
    -------
    DHSVMConfig
    """
    cfg = DHSVMConfig(name)
    state_dir = state_dir or output_dir

    # --- OPTIONS -----------------------------------------------------
    opts = {
        'Format': 'BIN',
        'Extent': 'BASIN',
        'Gradient': 'TOPOGRAPHY',
        'Flow Routing': 'NETWORK',
        'Sensible Heat Flux': False,
        'Overland Routing': 'CONVENTIONAL',
        'Interpolation': 'INVDIST',
        'Infiltration': 'STATIC',
        'MM5': False,
        'QPF': False,
        'PRISM': False,
        'PRISM data path': '',
        'PRISM data extension': '',
        'Gridded Met data': False,
        'Canopy radiation attenuation mode': 'FIXED',
        'Shading': shading,
        'Shading data path': paths.get('shadow_path', ''),
        'Shading data extension': 'bin' if shading else '',
        'Skyview data path': paths.get('skyview', ''),
        'Snotel': False,
        'Outside': False,
        'Rhoverride': False,
        'Precipitation Source': 'STATION',
        'Wind Source': 'STATION',
        'Temperature lapse rate': 'CONSTANT',
        'Precipitation lapse rate': 'CONSTANT',
        'Cressman radius': 10,
        'Cressman stations': 4,
        'Stream Temperature': False,
        'Riparian Shading': False,
        'Variable Light Transmittance': False,
        'Canopy Gapping': canopy_gapping,
        'Snow Sliding': False,
        'Routing Neighbors': routing_neighbors,
    }
    if options:
        opts.update(options)
    cfg.update('OPTIONS', opts)
    cfg.comment('OPTIONS',
                'Gridded Met data is deliberately FALSE: DHSVM\'s gridded path never '
                'assigns a station elevation, so it lapses temperature from sea level. '
                'Station mode lets every station carry its true DEM elevation.')

    # --- AREA ---------------------------------------------------------
    lat, lon = grid.centerLatLon()
    cfg.update('AREA', {
        'Coordinate System': 'UTM',
        'Extreme North': f'{grid.yurcorner:.8f}',
        'Extreme West': f'{grid.xllcorner:.8f}',
        'Center Latitude': f'{lat:.6f}',
        'Center Longitude': f'{lon:.6f}',
        # Forcing is written in UTC, so the clock's standard meridian is 0.
        'Time Zone Meridian': '0.0',
        'Number of Rows': grid.nrows,
        'Number of Columns': grid.ncols,
        'Grid spacing': f'{grid.cellsize:g}',
        'Point North': '',
        'Point East': '',
    })
    cfg.comment('AREA',
                'Extreme North/West are the grid CORNER coordinates (Map->Yorig / '
                'Map->Xorig); cell centres lie at Xorig+(col+0.5)*DX and '
                'Yorig-(row+0.5)*DY.  Time Zone Meridian is 0 because ww_dhsvm '
                'writes forcing timestamps in UTC.')

    # --- TIME ---------------------------------------------------------
    tfmt = '%m/%d/%Y-%H'
    cfg.update('TIME', {
        'Time Step': f'{timestep_hours:g}',
        'Model Start': start.strftime(tfmt),
        'Model End': end.strftime(tfmt),
    })

    # --- CONSTANTS ----------------------------------------------------
    consts = {
        'Ground Roughness': 0.02,
        'Snow Roughness': 0.01,
        'Rain Threshold': -1.0,
        'Snow Threshold': 1.0,
        'Snow Water Capacity': 0.03,
        'Reference Height': 45.0,
        'Rain LAI Multiplier': 0.0001,
        'Snow LAI Multiplier': 0.0005,
        'Min Intercepted Snow': 0.005,
        'Outside Basin Value': 0,
        'Temperature Lapse Rate': -0.0065,
        'Precipitation Lapse Rate': 0.0,
        'Precipitation Multiplier': 1.0,
        'Albedo Accumulation Lambda': 0.92,
        'Albedo Melting Lambda': 0.70,
        'Albedo Accumulation Min': 0.50,
        'Albedo Melting Min': 0.40,
        'Gap Wind Adj Factor': 1.0,
        'Snowslide Parameter1': 700,
        'Snowslide Parameter2': 0.12,
    }
    if constants:
        consts.update(constants)
    cfg.update('CONSTANTS', consts)
    cfg.comment('CONSTANTS',
                'Rain/Snow Threshold bracket a linear mixed-phase zone: below Rain '
                'Threshold all precipitation is snow, above Snow Threshold all is '
                'rain.  Reference Height must exceed the tallest canopy in the '
                '[VEGETATION] table.')

    # --- TERRAIN ------------------------------------------------------
    cfg.update('TERRAIN', {
        'DEM File': paths['dem'],
        'Basin Mask File': paths['mask'],
    })

    # --- ROUTING ------------------------------------------------------
    cfg.update('ROUTING', {
        'Stream Map File': paths['stream_map'],
        'Stream Network File': paths['stream_network'],
        'Stream Class File': paths['stream_class'],
        'Riparian Veg File': 'NA',
        'Travel Time File': '',
        'Unit Hydrograph File': '',
    })

    # --- METEOROLOGY --------------------------------------------------
    cfg.set('METEOROLOGY', 'Number of Stations', len(stations))
    for i, st in enumerate(stations, start=1):
        cfg.set('METEOROLOGY', f'Station Name     {i}', st.name)
        cfg.set('METEOROLOGY', f'North Coordinate {i}', f'{st.northing:.4f}')
        cfg.set('METEOROLOGY', f'East Coordinate  {i}', f'{st.easting:.4f}')
        cfg.set('METEOROLOGY', f'Elevation        {i}', f'{st.elevation:.4f}')
        cfg.set('METEOROLOGY', f'Station File     {i}', st.filename)
    cfg.comment('METEOROLOGY',
                'One block per forcing station.  Elevation is sampled from the model '
                'DEM at the station cell and is the reference for DHSVM\'s lapse-rate '
                'corrections, so it must be the DEM value, not the source dataset\'s.')

    # --- SOILS --------------------------------------------------------
    cfg.update('SOILS', {
        'Soil Map File': paths['soil'],
        'Soil Depth File': paths['soil_depth'],
        'Number of Soil Types': len(soil_blocks),
    })
    for b in soil_blocks:
        i = b['id']
        cfg.set('SOILS', f'#COMMENT_soil_{i}', f'---- Soil {i}: {b["description"]} ----')
        cfg.update('SOILS', {
            f'Soil Description       {i}': b['description'],
            f'Lateral Conductivity   {i}': b['lateral_conductivity'],
            f'Exponential Decrease   {i}': b['exponential_decrease'],
            f'Depth Threshold        {i}': b['depth_threshold'],
            f'Maximum Infiltration   {i}': b['max_infiltration'],
            f'Capillary Drive        {i}': b['capillary_drive'],
            f'Surface Albedo         {i}': b['surface_albedo'],
            f'Number of Soil Layers  {i}': b['n_layers'],
            f'Porosity               {i}': b['porosity'],
            f'Pore Size Distribution {i}': b['pore_size_distribution'],
            f'Bubbling Pressure      {i}': b['bubbling_pressure'],
            f'Field Capacity         {i}': b['field_capacity'],
            f'Wilting Point          {i}': b['wilting_point'],
            f'Bulk Density           {i}': b['bulk_density'],
            f'Vertical Conductivity  {i}': b['vertical_conductivity'],
            f'Thermal Conductivity   {i}': b['thermal_conductivity'],
            f'Thermal Capacity       {i}': b['thermal_capacity'],
            f'Residual Water Content {i}': b['residual_water_content'],
            f'Mannings n             {i}': b['mannings_n'],
        })
    cfg.comment('SOILS',
                'Lateral Conductivity and Exponential Decrease together set how '
                'saturated subsurface flow -- and therefore baseflow recession -- '
                'behaves.  They are the usual first targets for calibration.')

    # --- VEGETATION ---------------------------------------------------
    cfg.set('VEGETATION', 'Vegetation Map File', paths['veg'])
    if canopy_gapping and paths.get('canopy_gap'):
        cfg.set('VEGETATION', 'Canopy Gap Map File', paths['canopy_gap'])
    cfg.set('VEGETATION', 'Number of Vegetation Types', len(veg_blocks))

    # DHSVM requires an impervious-surface routing file as soon as ANY
    # vegetation type has a non-zero impervious fraction (InitTables.c).
    if any(b['impervious_fraction'] > 0 for b in veg_blocks):
        if not paths.get('impervious_routing'):
            raise ValueError(
                'One or more vegetation types have Impervious Fraction > 0, so '
                'DHSVM requires an IMPERVIOUS SURFACE ROUTING FILE.  Generate one '
                'with ww_dhsvm.streams.writeImperviousRoutingFile and pass it as '
                "paths['impervious_routing'].")
        cfg.set('VEGETATION', 'Impervious Surface Routing File',
                paths['impervious_routing'])

    for b in veg_blocks:
        i = b['id']
        cfg.set('VEGETATION', f'#COMMENT_veg_{i}',
                f'---- Vegetation {i}: {b["description"]} '
                f'(NLCD {b.get("nlcd_code", "?")}) ----')
        entries = {
            f'Vegetation Description        {i}': b['description'],
            f'Impervious Fraction           {i}': b['impervious_fraction'],
            f'Detention Fraction            {i}': b['detention_fraction'],
            f'Detention Decay               {i}': b['detention_decay'],
            f'Overstory Present             {i}': b['overstory'],
            f'Understory Present            {i}': b['understory'],
            f'Fractional Coverage           {i}': (b['fractional_coverage']
                                                   if b['overstory'] else ''),
            f'Hemi Fract Coverage           {i}': '',
            f'Clumping Factor               {i}': '',
            f'Leaf Angle A                  {i}': '',
            f'Leaf Angle B                  {i}': '',
            f'Scattering Parameter          {i}': '',
            f'Trunk Space                   {i}': (b['trunk_space']
                                                   if b['overstory'] else ''),
            f'Aerodynamic Attenuation       {i}': (b['aerodynamic_attenuation']
                                                   if b['overstory'] else ''),
            f'Radiation Attenuation         {i}': (b['radiation_attenuation']
                                                   if b['overstory'] else ''),
            f'Diffuse Radiation Attenuation {i}': (b['diffuse_radiation_attenuation']
                                                   if b['overstory'] else ''),
            f'Max Snow Int Capacity         {i}': (b['max_snow_int_capacity']
                                                   if b['overstory'] else ''),
            f'Mass Release Drip Ratio       {i}': (b['mass_release_drip_ratio']
                                                   if b['overstory'] else ''),
            f'Snow Interception Eff         {i}': (b['snow_interception_eff']
                                                   if b['overstory'] else ''),
            f'Height                        {i}': _heights(b),
            f'Overstory Monthly LAI         {i}': (b['overstory_monthly_lai']
                                                   if b['overstory'] else ''),
            f'Understory Monthly LAI        {i}': (b['understory_monthly_lai']
                                                   if b['understory'] else ''),
            f'Maximum Resistance            {i}': _pair(b, 'maximum_resistance'),
            f'Minimum Resistance            {i}': _pair(b, 'minimum_resistance'),
            f'Moisture Threshold            {i}': _pair(b, 'moisture_threshold'),
            f'Vapor Pressure Deficit        {i}': _pair(b, 'vapor_pressure_deficit'),
            f'Rpc                           {i}': _pair(b, 'rpc'),
            f'Overstory Monthly Alb         {i}': (b['overstory_monthly_alb']
                                                   if b['overstory'] else ''),
            f'Understory Monthly Alb        {i}': (b['understory_monthly_alb']
                                                   if b['understory'] else ''),
            f'Number of Root Zones          {i}': b['n_root_zones'],
            f'Root Zone Depths              {i}': b['root_zone_depths'],
            f'Overstory Root Fraction       {i}': (b['overstory_root_fraction']
                                                   if b['overstory'] else ''),
            f'Understory Root Fraction      {i}': (b['understory_root_fraction']
                                                   if b['understory'] else ''),
            f'Monthly Light Extinction      {i}': b['monthly_light_extinction'],
            f'Canopy View Adj Factor        {i}': b['canopy_view_adj_factor'],
        }
        if canopy_gapping:
            entries[f'Canopy Gap Diameter           {i}'] = (
                b['canopy_gap_diameter'] if b['overstory'] else '')
        cfg.update('VEGETATION', entries)

    # --- OUTPUT -------------------------------------------------------
    cfg.set('OUTPUT', 'Output Directory', _dirpath(output_dir))
    cfg.set('OUTPUT', 'Initial State Directory', _dirpath(state_dir))

    output_pixels = output_pixels or []
    cfg.set('OUTPUT', 'Number of Output Pixels', len(output_pixels))
    for i, px in enumerate(output_pixels, start=1):
        cfg.set('OUTPUT', f'North Coordinate {i}', f"{px['northing']:.4f}")
        cfg.set('OUTPUT', f'East Coordinate  {i}', f"{px['easting']:.4f}")
        cfg.set('OUTPUT', f'Name             {i}', px['name'])

    state_dates = state_dates or []
    cfg.set('OUTPUT', 'Number of Model States', len(state_dates))
    for i, d in enumerate(state_dates, start=1):
        cfg.set('OUTPUT', f'State Date               {i}', d.strftime(tfmt))

    map_variables = map_variables or []
    cfg.set('OUTPUT', 'Number of Map Variables', len(map_variables))
    for i, mv in enumerate(map_variables, start=1):
        cfg.set('OUTPUT', f'Map Variable             {i}', mv['id'])
        cfg.set('OUTPUT', f'Map Layer                {i}', mv.get('layer', 1))
        dates = mv['dates']
        cfg.set('OUTPUT', f'Number of Maps           {i}', len(dates))
        for j, d in enumerate(dates, start=1):
            cfg.set('OUTPUT', f'Map Date {j}               {i}', d.strftime(tfmt))

    cfg.set('OUTPUT', 'Number of Image Variables', 0)
    cfg.set('OUTPUT', 'Number of Graphics', 0)
    cfg.comment('OUTPUT',
                'DHSVM does not create its output directory: it must exist before '
                'the run, or initialization fails with "Cannot open file".')

    return cfg


def _heights(b) -> str:
    """``Height`` takes overstory then understory, omitting absent layers."""
    vals = []
    if b['overstory']:
        vals.append(b['height'][0])
    if b['understory']:
        vals.append(b['height'][1])
    return ' '.join(_fmt(v) for v in vals)


def _pair(b, key) -> str:
    """Two-layer parameters list overstory then understory, present layers only."""
    over, under = b[key]
    vals = []
    if b['overstory']:
        vals.append(over)
    if b['understory']:
        vals.append(under)
    return ' '.join(_fmt(v) for v in vals)


def _dirpath(p: str) -> str:
    """DHSVM concatenates output paths with filenames, so they need a trailing /."""
    return p if p.endswith(os.sep) else p + os.sep


def validateConfig(cfg: DHSVMConfig,
                   grid,
                   soil_blocks,
                   veg_blocks,
                   soil_map: Optional[np.ndarray] = None,
                   veg_map: Optional[np.ndarray] = None,
                   timestep_hours: float = 1.0) -> Dict[str, Any]:
    """Cross-check a configuration against the maps it refers to.

    These are the consistency rules DHSVM enforces at runtime -- but
    which it reports as bare error codes, often after several minutes of
    initialization.

    Returns
    -------
    dict
        ``'ok'``, ``'errors'``, ``'warnings'``.
    """
    errors, warnings = [], []

    n_soil = len(soil_blocks)
    n_veg = len(veg_blocks)

    if soil_map is not None:
        hi = int(soil_map.max())
        if hi > n_soil:
            errors.append(f'soil.bin contains class {hi} but Number of Soil Types '
                          f'is {n_soil} (InitTerrainMaps.c error 32)')
        if int(soil_map.min()) < 1:
            errors.append('soil.bin contains class 0; DHSVM soil classes start at 1')

    if veg_map is not None:
        hi = int(veg_map.max())
        if hi > n_veg:
            errors.append(f'veg.bin contains class {hi} but Number of Vegetation '
                          f'Types is {n_veg}')
        if int(veg_map.min()) < 1:
            errors.append('veg.bin contains class 0; DHSVM vegetation classes '
                          'start at 1')

    soil_layers = {b['n_layers'] for b in soil_blocks}
    if len(soil_layers) > 1:
        errors.append(f'Soil types declare differing layer counts {soil_layers}; '
                      f'DHSVM requires one value for all soils')
    root_zones = {b['n_root_zones'] for b in veg_blocks}
    if soil_layers and root_zones and soil_layers != root_zones:
        errors.append(f'Number of Soil Layers {soil_layers} does not match '
                      f'Number of Root Zones {root_zones}')

    ref_height = None
    for k, v in cfg.sections['CONSTANTS']:
        if k.strip().lower() == 'reference height':
            ref_height = float(v)
    if ref_height is not None:
        tallest = max(b['height'][0] for b in veg_blocks)
        if ref_height <= tallest:
            errors.append(f'Reference Height {ref_height} m must exceed the tallest '
                          f'canopy ({tallest} m)')

    if 24.0 % timestep_hours > 1e-9:
        warnings.append(f'Time Step {timestep_hours} h does not divide 24 h evenly; '
                        f'DHSVM\'s daily aggregation will be uneven')

    ok = len(errors) == 0
    if ok:
        logging.info(f'  configuration validated: {n_soil} soil types, '
                     f'{n_veg} vegetation types, consistent with the maps')
    for e in errors:
        logging.error(f'  CONFIG ERROR: {e}')
    for w in warnings:
        logging.warning(f'  config warning: {w}')
    return dict(ok=ok, errors=errors, warnings=warnings)
